nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  # Autoriser toutes les origines (à adapter en production)
        allow_headers: ['*']  # Autoriser tous les en-têtes
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']  # Autoriser ces méthodes
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['http://127.0.0.1:3000']  # Autoriser uniquement ton frontend
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600